#
# JDBC properties
#
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

#
# Simple Spring Security configuration
#
spring.security.user.name=prado
spring.security.user.password=admin

logging.level.org.springframework.security=DEBUG