spring:
  application:
    name: cruddemo
  datasource:
    url: jdbc:mysql://localhost:3306/employee_directory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: springstudent
    password: springstudent
  jpa:
    show-sql: true
