spring.application.name=thymeleafdemo
countries=Brazil,France,Germany,India,Japan,United States
languages=Go,Java,JavaScript,Python,TypeScript,Rust
operationsSystems=Linux,MacOS,Microsoft Windows, Android OS, iOS, Chrome OS